name: Go

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16' # Use the version of Go you need

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test ./...